# Generated by Django 4.1.4 on 2023-01-03 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='car_images',
        ),
    ]
